from turtle import *
canvas = Screen()
canvas.setup(800,600)
jimmy = Turtle()
jimmy.shape("turtle")
jimmy.color("green")
jimmy.forward(30)
jimmy.right(90)
jimmy.forward(90)
jimmy.right(45)
jimmy.forward(15)
jimmy.right(45)
jimmy.forward(15)
jimmy.left(90)
jimmy = Turtle()
jimmy.shape("turtle")
jimmy.color("green")
jimmy.forward(60)
jimmy.right(90)
jimmy.forward(100)
jimmy = Turtle()
jimmy.shape("turtle")
jimmy.color("green")
jimmy.forward(100)
jimmy.right(135)
jimmy.forward(20)
jimmy.left(45)
jimmy.forward(85)
jimmy = Turtle()
jimmy.shape("turtle")
jimmy.color("green")
jimmy.forward(120)
jimmy.right(135)
jimmy.forward(20)
jimmy.left(45)
jimmy.forward(85)
jimmy = Turtle()
jimmy.shape("turtle")
jimmy.color("green")
jimmy.forward(140)
jimmy.right(135)
jimmy.forward(20)
jimmy.left(45)
jimmy.forward(85)
jimmy = Turtle()
jimmy.shape("turtle")
jimmy.color("green")
jimmy.forward(170)
jimmy.right(135)
jimmy.forward(20)
jimmy.left(45)
jimmy.forward(85)
jimmy = Turtle()
jimmy.shape("turtle")
jimmy.color("green")
jimmy.forward(190)
jimmy.right(135)
jimmy.forward(20)
jimmy.left(45)
jimmy.forward(85)
jimmy = Turtle()
jimmy.shape("turtle")
jimmy.color("green")
jimmy.forward(210)
jimmy.right(135)
jimmy.forward(20)
jimmy.left(45)
jimmy.forward(85)
jimmy = Turtle()
jimmy.shape("turtle")
jimmy.color("green")
jimmy.forward(220)
jimmy.right(45)
jimmy.forward(25)
jimmy.left(90)
jimmy.forward(25)
jimmy.backward(25)
jimmy.right(135)
jimmy.forward(80)
