from turtle import *
canvas = Screen()
canvas.setup(1000,500)
melissa = Turtle()
melissa.shape ("turtle")
melissa.color("blue")
melissa.up
melissa.left(60)
melissa.forward(90)
melissa.down
melissa.right(120)
melissa.forward(35)
melissa.up
melissa.left(120)
melissa.forward(35)
melissa.down
melissa.right(120)
melissa.forward(90)

melissa.color("white")
melissa.left(60)
melissa.forward(25)
melissa.left(90)
melissa.forward(30)
melissa.right(90)
               
melissa.color("blue")
melissa.forward(45)
melissa.left(130)
melissa.forward(20)
melissa.left(25)
melissa.forward(5)
melissa.left(25)
melissa.forward(5)
melissa.left(25)
melissa.forward(5)
melissa.left(15)
melissa.forward(20)
melissa.left(45)
melissa.forward(15)
melissa.left(25)
melissa.forward(15)
melissa.left(30)
melissa.forward(15)
melissa.left(35)
melissa.forward(15)
melissa.left(15)
melissa.forward(10)

melissa.color("white")
melissa.right(10)
melissa.forward(30)
melissa.left(90)

melissa.color("blue")
melissa.forward(80)

melissa.color("white")
melissa.right(135)
melissa.forward(30)

melissa.color("blue")
melissa.right(45)
melissa. forward(5)
melissa.color("white")
melissa.forward(10)
melissa.color("blue")
melissa.forward(45)

melissa.color("white")
melissa.left(90)
melissa.forward(20)
